config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'sessions/new'

  root 'welcome#index'
  get  '/signup',  to: 'users#new'
  get 'welcome/index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :events do
    resources :comments
    resources :tickets
  end

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  validates :department, presence: true, length: { minimum: 5}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  ratyrate_rater

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save # returns false if invalid
      log_in @user
      redirect_to events_path
    else
      render 'errors'
    end

  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :department)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def attending_events
    my_tickets = Ticket.where(:user_id => current_user.id).select(:event_id).all
    my_events = []
    my_tickets.each do |ticket|
      puts ticket.event_id
      my_events << Event.where(:id => ticket.event_id).first
    end
    return my_events
  end

  def has_ticket?(event)
    !Ticket.where(:event_id => event.id, :user_id => current_user.id).all.blank?
  end

  def hosting_events
    my_events = Event.where(:host_user_id => current_user.id)
    return my_events
  end
end

app/views/users/_attending.html.erb
<p></p>
<table class="table">
  <thead>
  <tr>
    <th>Event Title</th>
    <th>Event Date</th>
    <th>Event Page</th>
  </tr>
  </thead>
  <tbody>
  <% attending_events.each do |event| %>

      <tr>
        <td><%= event.title %></td>
        <td><%= event.start_date %></td>
        <td><%= link_to event_path(event), :class => "btn btn-primary" do %>
              Details
          <% end %>
        </td>
      </tr>


  <% end %>
  </tbody>
</table>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <h3>b@UCL</h3>
    <%= f.text_field :name %>
    <%= f.label :name %>

    <%= f.text_field :department %>
    <%= f.label :department %>

    <%= f.email_field :email %>
    <%= f.label :email %>

    <%= f.password_field :password %>
    <%= f.label :password, "Password. Min: 6 characters" %>

    <%= f.password_field :password_confirmation %>
    <%= f.label :password_confirmation, "Confirmation" %>

    <br>

    <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/_hosting.html.erb
<p></p>
<table class="table">
  <thead>
  <tr>
    <th>Event Title</th>
    <th>Event Date</th>
    <th>Event Page</th>
  </tr>
  </thead>
  <tbody>
  <% hosting_events.each do |event| %>
      <tr>

        <td><%= event.title %></td>
        <td><%= event.start_date %></td>
        <td><%= link_to event_path(event), :class => "btn btn-primary" do %>
              Details
          <% end %>
        </td>
      </tr>


  <% end %>
  </tbody>
</table>

app/views/users/errors.html.erb
<%= render 'shared/error_messages' %>

<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<p></p>

<% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <br>
      <td><%= user.email %></td>
      <br>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr><br><br>
<% end %>
<p></p>
<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<br><br>


<div class="container">
  <!--First row-->
  <div class="row">
    <div class="col-md-12">
      <div class="jumbotron">
        <h1 class="h1-responsive">
          <%= @user.name %>
        </h1>
        <p>Department: <%= @user.department %></p>
      </div>

      <div class="jumbotron">
        <h2 class="h2-responsive">
          Attending
        </h2>

        <p>
          <%= render 'attending' %>

        </p>

      </div>

      <div class="jumbotron">
        <h2 class="h2-responsive">
          Hosting
        </h2>

        <p>
        <%= render 'hosting' %>

        </p>

      </div>

    </div>
  </div>

</div>