config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'sessions/new'

  root 'welcome#index'
  get  '/signup',  to: 'users#new'
  get 'welcome/index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :events do
    resources :comments
    resources :tickets
  end

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # TODO: Maybe add if-statements here to check if user is already logged in. In the future.
    @user = User.new
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<!--Navbar-->
<nav class="navbar navbar-dark navbar-fixed-top">

  <div class="container" id="home-only-navbar">
      <!--Navbar Brand-->
      <a class="navbar-brand" href="/">b@UCL</a>
      <!--Links-->
      <ul class="nav navbar-nav">
        <% if logged_in? %>
            <li><%= link_to "Events", events_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>


        <% else %>
            <li><%= link_to "Log in", root_path %></li>
        <% end %>
      </ul>
    </div>
    <!--/.Collapse content-->


</nav>
<!--/.Navbar-->

<!--Navigation & Intro-->
<header>
  <!--Mask-->
  <div class="view hm-black-strong">
    <div class="full-bg-img flex-center">
      <ul>
        <li>
          <h1 class="h1-responsive wow fadeInUp">Booking @ UCL</h1></li>
        <% unless logged_in? %>
        <li class="wow fadeInUp" data-wow-delay="0.4s">

          <a class="btn btn-white-outline btn-lg" id="signup"><i class="fa fa-user left"></i> Sign up</a>
          <a class="btn btn-white-outline btn-lg" id="login"><i class="fa fa-book left"></i>Log in</a>
        </li>
        <% end %>

        <!--<li class="wow fadeInUp" data-wow-delay="0.6s" >-->
          <!--<%= link_to controller: 'events' do %>-->
              <!--<span class="btn btn-white-outline btn-lg">Events (temporary link)</span>-->
          <!--<% end %>-->
        <!--</li>-->
        <!--<li class="wow fadeInUp" data-wow-delay="0.8s">-->
          <!--<%= link_to controller: 'users' do %>-->
              <!--<span class="btn btn-white-outline btn-lg">List of users</span>-->
          <!--<% end %>-->
        <!--</li>-->
      </ul>


    </div>
  </div>
  <!--/.Mask-->

  <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="signup-modal">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= render '/users/form', :user => @user %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="login-modal">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= render '/sessions/form' %>
          </div>
        </div>
      </div>
    </div>
  </div>


</header>

<!--/Navigation & Intro-->