config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'sessions/new'

  root 'welcome#index'
  get  '/signup',  to: 'users#new'
  get 'welcome/index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :events do
    resources :comments
    resources :tickets
  end

  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :tickets, dependent: :destroy
  # has_one :category
  # for length specification use this syntax
  validates :title, :text, presence: true, length: { minimum: 5, maximum: 2000}
  validates :available_tickets, presence: true

  def self.search(search)
    where("title LIKE ? OR category LIKE ? OR text LIKE ? ", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  ratyrate_rateable 'overall_score', 'vibes', 'location', 'tech_equipment', 'internet'


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  # For basic authentication
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    # @events = Event.all

    # Relict from search by date
    # @search = Event.new(params[:search])
    # @events = @search.scope

    if params[:search]
      @events = Event.search(params[:search]).order("created_at DESC")
    else
      @events = Event.all.order('created_at DESC')
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    if logged_in?
      @event.host_user_id = current_user.id
    end
    @event.tickets_sold = 0
    if @event.save # returns false if invalid
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params) # It is not necessary to pass all the attributes to update. For example, if @article.update(title: 'A new title') was called, Rails would only update the title attribute, leaving all other attributes untouched.
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  private
  def event_params
    params.require(:event).permit(:title, :text, :street, :street_number, :city, :start_date, :end_date, :available_tickets, :start_time, :end_time, :category, :user_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def tickets_left?
    unless @event.available_tickets.nil?
      @event.available_tickets > 0
    end
  end

  def time_surpassed?
    !@event.end_date.to_date.past?
  end

  def is_host?
    @event.host_user_id == current_user.id
  end

  def progress_bar_width(event)
    ((event.tickets_sold / (event.available_tickets + event.tickets_sold))*100).round(1)
  end

  def send_emails_if_event_near

    my_tickets = Ticket.where(:user_id => current_user.id).select(:event_id).all
    my_events = []
    my_tickets.each do |ticket|
      puts ticket.event_id
      my_events << Event.where(:id => ticket.event_id).first
    end

    if my_events[0].start_date.to_date == DateTime.now.to_date-2

      #send email when user is logged in and event is two days away
      #we experimented with cron jobs and managed to send local emails
      respond_to do |format|

        # Sends email to user when user is created.
        ExampleMailer.sample_email(@user).deliver_now

        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }

      end
    end

  end

    #
    # # Sends email to user when user is created.
    # puts "Background task is running!"
    #
    # user = @user.current_user
    #
    # respond_to do |format|
    #
    #   ExampleMailer.sample_email(user).deliver_now
    #   format.html { redirect_to user }
    #   format.json { render :show, status: :created, location: @user }
    #
    # end

end

app/views/events/_attending_users.html.erb
<p></p>
<table class="table">
  <thead>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Department</th>
    <th>Profile</th>
  </tr>
  </thead>
  <tbody>
  <% attending_guests(@event).each do |user| %>

      <tr>
        <td><%= user.name %></td>
        <td><%= user.department %></td>
        <td><%= link_to user_path(user), :class => "btn btn-primary" do %>
              Details
          <% end %>
        </td>
      </tr>


  <% end %>

  </tbody>
</table>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

    <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@event.errors.count, "error") %>
            prohibited this event from being saved:
          </h2>
          <ul>
            <% @event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="jumbotron">
    <h3>Title and description</h3>


    <div class="md-form">
      <%= f.label :title, value: "Event title"%>
      <br>
      <%= f.text_field :title%>
    </div>

    <div class="md-form">
      <%= f.label :text, value: "Description" %>
      <br>
      <%= f.text_field :text%>
    </div>
    </div>

    <div class="jumbotron">
    <div class="display-section">
      <h3>Location</h3>
    </div>
    <!--<input id="pac-input" class="controls" type="text"-->
           <!--placeholder="Enter a location">-->
    <!--<div id="map">-->
    <!--</div>-->

    <br>
    <div class="md-form">
      <%= f.label :street, value: "Street name" %>
      <br>
      <%= f.text_field :street %>
    </div>

    <div class="md-form">
      <%= f.label :street_number, value: "Street number or house" %>
      <br>
      <%= f.text_field :street_number %>
    </div>

    <div class="md-form">
      <%= f.label :city, value: "City" %>
      <br>
      <%= f.text_field :city %>
    </div>
      </div>

      <div class="jumbotron">
    <h3>Date and time, category and # of tickets</h3>

    <p>
      <br>
      <%= f.label :start_time, value: "Start time" %>
      <%= f.time_select :start_time%>

      <%= f.label :start_date, value: "Start date" %>
      <%= f.date_select :start_date, :start_year => 1900%>

    </p>

    <p>
      <br>
      <%= f.label :end_time%>
      <%= f.time_select :end_time%>

      <%= f.label :end_date %>
      <%= f.date_select :end_date%>
    </p>

    <br>
    <div class="md-form">
      <%= f.label :available_tickets, value: "Tickets", :id => "ticket_label" %>
      <br>
      <%= f.number_field :available_tickets, :class => "required"%>
    </div>

    <p>
      <%= f.label "Category" %>
      <br>
      <%= f.select(:category, options_for_select([["Study session", "Study session"], ["Group meeting", "Group meeting"],
                                                 ["Guest talk", "Guest talk"], ["Other", "Other"]]))%>
    </p>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="jumbotron">
          <p class="lead">
            <%= f.submit 'Create', class: "btn btn-primary" %>
          </p>
        </div>
      </div>
    </div>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUHGDBmVqTToBoTTppgJBDjY3ESGLmItQ&libraries=places&callback=initMap"
            async defer></script>

<% end %>

app/views/events/_search.html.erb
<% @events.each do |event| %>
    <!--First columnn-->
    <div class="col-md-4">
      <!--Card-->
      <div class="card">

        <!--Card image-->
        <div class="view overlay hm-white-slight">
          <%= link_to event_path(event) do %>
              <!--<img src="http://mdbootstrap.com/images/regular/city/img%20(2).jpg" class="img-fluid" alt="">-->
          <% end %>
        </div>
        <!--/.Card image-->

        <!--Card content-->
        <div class="card-block">
          <!--Title-->
          <h3 class="card-title"><em><%= event.title %></em></h3>
          <!--Text-->
          <p>Where? <%= event.street %>, <%= event.city %> </p>
          <p>When? <%= event.start_date.to_date %></p>

          <%= link_to event_path(event), :class => "btn btn-primary" do %>
              Read more
          <% end %>
        </div>
        <!--/.Card content-->

      </div>
      <!--/.Card-->
    </div>
    <!--First columnn-->
<% end %>

app/views/events/edit.html.erb
<!--Navbar-->
<%= render 'layouts/header' %>
<!--/.Navbar-->
<br><br>

<div class="jumbotron-col-lg-6-col-centered">
  <h1 class="h1-responsive">Edit Event</h1>
  <%= link_to 'Back', events_path, class: "btn btn-primary" %>

  <%= render 'form' %>

</div>

app/views/events/index.html.erb
<!--Navbar-->
<%= render 'layouts/header' %>
<!--/.Navbar-->
<br><br>
<main>

  <!--Main layout-->
  <div class="container">
    <!--First row-->
    <div class="row">
      <div class="col-md-12">
        <div class="jumbotron">
          <h2 class="h2-responsive">Booking @ UCL</h2>

          <p class="lead">
          <%= link_to new_event_path, :class => "btn btn-primary" do %>
            New Event
          <% end %>
          </p>
        </div>
      </div>
    </div>
    <!--/.First row-->

    <div class="row">
      <div class="col-md-12">
        <div class="jumbotron">
          <h2 class="h2-responsive">Search</h2>
          <br>

          <p class="lead">
          <%= form_tag(events_path, :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search Events (title, description or category)" %>
              <br><br>
              <%= submit_tag "Search", :class => "btn btn-primary" %>
          <% end %>
          </p>

        </div>

      </div>
    </div>

    <div class="row">
          <% if @events.present? %>
              <%= render 'search' %>
          <% else %>
              <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
          <% end %>
    </div>


    <!--/.Second row-->
  </div>
  <!--/.Main layout-->

</main>

app/views/events/new.html.erb
<!--Navbar-->
<%= render 'layouts/header' %>
<!--/.Navbar-->
<br><br>

<div class="jumbotron-col-lg-6-col-centered">
  <h1 class="h1-responsive">New Event</h1>
  <p class="lead">Create your event with a lit title and appropriate description</p>
  <%= link_to 'Back', events_path, class: "btn btn-primary" %>
  <%= render 'form' %>



</div>

app/views/events/show.html.erb
<!--Navbar-->
<%= render 'layouts/header' %>
<!--/.Navbar-->
<br><br>
<main>
  <div class="jumbotron-col-lg-6-col-centered">
    <!--First row-->

    <%= link_to events_path, :class => "btn btn-primary" do %>
        Back
    <% end %>

    <% if flash[:notice] %>
        <div class="jumbotron" style="background-color:greenyellow;">
          <h2 class="h2-responsive">
            <div class="notice"><%= flash[:notice] %></div>
          </h2>
        </div>
    <% end %>




    <div class="jumbotron">

      <h2 class="h2-responsive"><%= @event.title %></h2>
      <br>
      <h4><%= @event.text %></h4>
    </div>

    <div class="jumbotron">
      <h2 class="h2-responsive">Location</h2>
      <br>
      <h4><%= @event.street %>, <%= @event.street_number %></h4>
      <%= @event.city %>

    </div>

    <div class="jumbotron">
      <h2 class="h2-responsive">Time & Tickets</h2>
      <br>
      <h4>From: <%= @event.start_date.to_date %>, <%= @event.start_time.strftime("%I:%M%p") %></h4>
      <h4>To: <%= @event.end_date.to_date %>, <%= @event.end_time.strftime("%I:%M%p") %></h4>
      <h4>Number of tickets available: <%= @event.available_tickets %></h4>
    </div>
    <br>

    <% if !time_surpassed? %>
        <div class="jumbotron">

          <h2>Comments & Ratings</h2>

          Original: <%= rating_for @event, "overall_score", disable_after_rate: true, imdb_avg: true, cancel_place: 'right' %>


          <% if logged_in? %>
              <br>
              Vibes: <%= rating_for @event, "vibes", enable_half: true, cancel_place: 'right' %>
              <br>
              Location: <%= rating_for @event, "location", enable_half: true, cancel_place: 'right' %>
              <br>
              Technical equipment: <%= rating_for @event, "tech_equipment", enable_half: true, cancel_place: 'right' %>
              <br>
              Internet: <%= rating_for @event, "internet", enable_half: true, cancel_place: 'right' %>
              <br>
          <% end %>
          <br>

          <%= render @event.comments %>

          <% if logged_in? %>
              <h2>Add a comment:</h2>
              <%= render 'comments/form' %>
          <% end %>


        </div>
    <% end %>
    <% if logged_in? %>
        <div class="jumbotron">
          <% if is_host? %>
              <%= link_to edit_event_path(@event), :class => "btn btn-primary" do %>
                  Edit event
              <% end %>
          <% end %>

          <% unless has_ticket?(@event) %>
              <% if time_surpassed? %>
                  <% if tickets_left? %>
                      <%= link_to event_tickets_path(@event, ticket: {user_id: current_user.id}), :class => "btn btn-primary", method: :post do %>
                          Book ticket
                      <% end %>
                  <% end %>
              <% end %>
          <% end %>
    <% end %>

    </div>

    <% if logged_in? %>
        <% if is_host? %>
            <div class="jumbotron">
              <h2>Progress of ticket sales</h2>
              <div class="row">
                <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="<%= @event.tickets_sold %>" aria-valuemin="0" aria-valuemax="<%= @event.available_tickets + @event.tickets_sold %>" style="min-width: 2em; width: <%= progress_bar_width(@event) %>%;" >
                    <%= @event.tickets_sold %> (<%= progress_bar_width(@event) %> %)
                  </div>
                </div>
              </div>
              <br>
              <div class="row">
                <h2>Users coming to your event</h2>
                <%= render 'attending_users' %>
              </div>
            </div>
        <% end %>
    <% end %>

  </div>


</main>